all: flash_stats

flash_stats: SS-A SS-B SS-C SS-D SS-E SS-F SS-G SS-H SS-I SS-J SS-K

SS-A:
	python3 main.py "-f ../data/flash/SS-A.csv"

SS-B:
	python3 main.py "-f ../data/flash/SS-B.csv"

SS-C:
	python3 main.py "-f ../data/flash/SS-C.csv"

SS-D:
	python3 main.py "-f ../data/flash/SS-D.csv"

SS-E:
	python3 main.py "-f ../data/flash/SS-E.csv"

SS-F:
	python3 main.py "-f ../data/flash/SS-F.csv"

SS-G:
	python3 main.py "-f ../data/flash/SS-G.csv"

SS-H:
	python3 main.py "-f ../data/flash/SS-H.csv"

SS-I:
	python3 main.py "-f ../data/flash/SS-I.csv"

SS-J:
	python3 main.py "-f ../data/flash/SS-J.csv"

SS-K:
	python3 main.py "-f ../data/flash/SS-K.csv"
