name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run gate.py
      run: |
        cd src
        python3 gate.py -t all

    - name: Run mylo.py
      run: |
        cd src
        python3 mylo.py -t all
