name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run gate.py
      run: |
        cd hw/src
        python3 gate.py -t all

    - name: Run mylo.py
      run: |
        cd hw/src
        python3 mylo.py -t all
